import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Panaderia',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="gif-background"></div> {/* Added a separate div for the fixed background */}
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
